courses/urls.py
from django.conf.urls import url

from views import CourseListView ,CourseDetailView,\
                  CourseCreateView,CourseUpdateView,\
                  CourseDeleteView,LectureDetailView,CoursePurchaseView
    

urlpatterns = [
    url(r'^$', CourseListView.as_view(), name='list'),
    url(r'^create/$', CourseCreateView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', CourseDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/purchase/$', CoursePurchaseView.as_view(), name='purchase'),
    url(r'^(?P<slug>[\w-]+)/edit/$', CourseUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', CourseDeleteView.as_view(), name='delete'),
    url(r'^(?P<cslug>[\w-]+)/(?P<lslug>[\w-]+)/$',LectureDetailView.as_view(), name='lecture-detail'),



]

sharing/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from .views import HomeView,home

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',HomeView.as_view(),name="home"),
    url(r'^videos/',include('videos.urls',namespace="videos")),
    url(r'^courses/',include('courses.urls',namespace="courses")),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

videos/urls.py
from django.conf.urls import url
from django.contrib import admin


from views import VideoListView, VideoDetailView,\
                  VideoCreateView,VideoUpdateView,\
                  VideoDeleteView

urlpatterns = [
    url(r'^$', VideoListView.as_view(), name='list'),
    url(r'^create/$', VideoCreateView.as_view(), name='create'),
    # url(r'^videos/(?P<pk>\d+)/$', VideoDetailView.as_view(), name='video-detail'),
    url(r'^(?P<slug>[\w-]+)/$', VideoDetailView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', VideoUpdateView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', VideoDeleteView.as_view(), name='delete'),

]

courses/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from utils import create_slug,make_display_price
from videos.models import Video
from django.db.models import Prefetch

# My Courses
class MyCourses(models.Model):
    user            = models.OneToOneField(settings.AUTH_USER_MODEL)
    courses         = models.ManyToManyField('Course',related_name="owned", blank=True)
    updated         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.courses.all().count()

    class Meta:
        verbose_name = 'My courses'
        verbose_name_plural = 'My courses'

def post_save_user_create(sender, instance, created, *args, **kwargs):
    if created:
        MyCourses.objects.get_or_create(user=instance)

post_save.connect(post_save_user_create, sender=settings.AUTH_USER_MODEL)


class CourseQuerySet(models.query.QuerySet):

	def active(self):
		return self.filter(active=True)

	def owned(self,user):
		return self.prefetch_related(
				Prefetch('owned',
						  queryset=MyCourses.objects.filter(user=user),
						  to_attr='is_owner'

				)
			)

class CourseManager(models.Manager):
	def get_queryset(self):
		return CourseQuerySet(self.model,using=self._db)

	def all(self):
		return self.get_queryset().all().active()	 				

# Course Model
class Course(models.Model):
    user            = models.ForeignKey(settings.AUTH_USER_MODEL)
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True)
    description     = models.TextField()
    price           = models.DecimalField(decimal_places=2,max_digits=6)
    updated         = models.DateTimeField(auto_now=True)
    active 			= models.BooleanField(default=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    objects=CourseManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
    	return reverse("courses:detail",kwargs={"slug":self.slug})

    def get_purchase_url(self):
    	return reverse("courses:purchase",kwargs={'slug':self.slug})	 

    def display_price(self):
    	return make_display_price(self.price)	   


# Lecture model
class Lecture(models.Model):
    course          = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True)
    video           = models.ForeignKey(Video, on_delete=models.SET_NULL, null=True)
    title           = models.CharField(max_length=120)
    slug            = models.SlugField(blank=True) # unique = False
    description     = models.TextField()
    updated         = models.DateTimeField(auto_now=True)
    timestamp       = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
    	unique_together=(('slug','course'),)    

    def get_absolute_url(self):
		return reverse("courses:lecture-detail", 
						kwargs={"cslug": self.course.slug,
								 "lslug": self.slug})

def pre_save_video_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_video_receiver, sender=Course)

courses/forms.py
from django import forms

from models import Course,Lecture
from videos.models import Video

class LectureAdminForm(forms.ModelForm):
    class Meta:
        model=Lecture
        fields=['title','slug','description','video']

    def __init__(self, *args, **kwargs):
        super(LectureAdminForm, self).__init__(*args, **kwargs)
        obj = kwargs.get("instance")
        print obj
        qs = Video.objects.filter(lecture__isnull=True)
        if obj:
            if obj.video:
                this_ = Video.objects.filter(pk=obj.video.pk)
                qs = (qs | this_)
            self.fields['video'].queryset = qs
        else:
            self.fields['video'].queryset = qs


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = [
            'title',
            'description',
            'slug',
            'price',]

    def clean_slug(self):
        slug=self.cleaned_data.get("slug")
        qs=Course.objects.filter(slug=slug)
        if qs.count()>1:
            raise forms.ValidationError("Slug must be unique")
        return slug         

courses/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import (
	CreateView,
	DetailView,
	UpdateView,
	ListView,
	DeleteView,
	RedirectView
	)
from django.http import Http404
from models import Course,MyCourses
from django.contrib.auth.mixins import LoginRequiredMixin
from videos.mixins import MemberRequiredMixin, StaffMemberRequiredMixin
from forms import CourseForm
from django.db.models import Prefetch


# Create
class CourseCreateView(StaffMemberRequiredMixin,CreateView):
	model=Course
	form_class=CourseForm
	success_url='/success/'

	def form_valid(self,form):
		obj=form.save(commit=False)
		obj.user=self.request.user
		obj.save()

		return super(CourseCreateView,self).form_valid(form)


# Lecture Detail
class LectureDetailView(MemberRequiredMixin,DetailView):
	def get_object(self):
		course_slug=self.kwargs.get("cslug")
		lecture_slug=self.kwargs.get("lslug")
		obj=get_object_or_404(Lecture,course__slug=course_slug,slug=lecture_slug)
		return obj


# Detail
class CourseDetailView(MemberRequiredMixin,DetailView):
	queryset=Course.objects.all()

	def get_object(self):
		slug=self.kwargs.get("slug")
		obj=Course.objects.filter(slug=slug)
		if obj.exists():
			return obj.first()
		raise Http404	


# List
class CourseListView(ListView):
	def get_queryset(self):
		request=self.request
		qs=Course.objects.all()
		query=request.GET.get('q')
		user=self.request.user
		if query:
			qs=qs.fiter(title__icontains=query)

		if user.is_authenticated():
			qs=qs.owned(user)
		return qs

# Purchase
class CoursePurchaseView(LoginRequiredMixin,RedirectView):
	permanent=False



# Update
class CourseUpdateView(StaffMemberRequiredMixin,UpdateView):
	queryset=Course.objects.all()
	form_class=CourseForm

	def form_valid(self,form):
		obj=form.save(commit=False)
		if not self.request.user.is_staff:
			obj.user=self.request.user
		obj.save()
		
		return super(CourseUpdateView,self).form_valid(form)	


	def get_object(self):
		slug=self.kwargs.get("slug")
		obj=Course.objects.filter(slug=slug)
		if obj.exists():
			return obj.first()
		raise Http404


# Delete
class CourseDeleteView(StaffMemberRequiredMixin,DeleteView):
	queryset=Course.objects.all()
	success_url='/videos/'

	def get_object(self):
		slug=self.kwargs.get("slug")
		obj=Course.objects.filter(slug=slug)
		if obj.exists():
			return obj.first()
		raise Http404

courses/templates/courses/course_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Videos | {{ block.super }}{% endblock title %}


{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<form method='POST' action=''>{% csrf_token %}
		        <p>Are you sure you want to delete <b>{{ object.title }}</b>?</p>
		        <input type='submit' value='Yes' class='btn btn-default' />
		        <a href='{{ object.get_absolute_url }}'>Cancel</a>
    		</form>
		</div>
	</div>
    
{% endblock content %}

courses/templates/courses/course_detail.html
{% extends 'base.html' %}

{% block title %}Videos | {{ block.super }}{% endblock title %}


{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			{% include 'videos/snippets/video-search-form.html' with request=request %}

		    <h1>Hi</h1>

		    {{ object.title }}
		    {{ object.embed_code|safe }}
		    {{ object.updated }}
		    {{ object.id }}
		</div>
	</div>
	
{% endblock content %}

courses/templates/courses/course_form.html
{% extends 'base.html' %}

{% block title %}Videos | {{ block.super }}{% endblock title %}


{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<form method='POST' action=''>{% csrf_token %}
	        	{{ form.as_p }}
	        	<input type='submit' value='Save' class='btn btn-default' />
    		</form>
		</div>
	</div>

{% endblock content %}

courses/templates/courses/course_list.html
{% extends 'base.html' %}

{% block title %}Courses | {{ block.super }}{% endblock title %}


{% block content %}
    <div class='row'>
        <div class='col-sm-6 col-sm-offset-3'>
            <h1>Hi</h1>

            {% if request.GET.q %}
                <p>You searched for <b>{{ request.GET.q }}</b></p>
            {% endif %}
            <ul>
                {% for item in object_list %}
                    <li>
                        <a href='{{ item.get_absolute_url }}'>{{ item.title }}
                        </a> 
                        <small>{{ item.lecture_set.count }} lectures</small> | 
                        
                        {% if item.is_owner %}
                            owned
                        {% else %}    
                            {{ item.display_price }}

                        {% endif %}
                    </li>
                
                {% empty %}
                    <li>No item found</li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}

courses/templates/courses/lecture_detail.html
{% extends 'base.html' %}

{% block title %}Videos | {{ block.super }}{% endblock title %}


{% block content %}
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			{% include 'videos/snippets/video-search-form.html' with request=request %}

		    <h1>Hi</h1>

		    {{ object.title }}
		    {{ object.embed_code|safe }}
		    {{ object.updated }}
		    {{ object.id }}
		</div>
	</div>
	
{% endblock content %}